name: Test

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [uipath-ubuntu-latest, uipath-windows-latest]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0

      - name: Setup uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        if: "!(matrix.os == 'uipath-ubuntu-latest' && matrix.python-version == '3.13')"
        run: uv run pytest

      - name: Run tests with coverage
        if: matrix.os == 'uipath-ubuntu-latest' && matrix.python-version == '3.13'
        run: uv run pytest --cov-report=xml --cov-report=html --tb=short

      - name: Upload coverage HTML report
        if: matrix.os == 'uipath-ubuntu-latest' && matrix.python-version == '3.13' && always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: coverage-html-report
          path: htmlcov/
          retention-days: 30

      - name: Upload coverage XML report
        if: matrix.os == 'uipath-ubuntu-latest' && matrix.python-version == '3.13' && always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: coverage-xml-report
          path: coverage.xml
          retention-days: 30

    continue-on-error: true

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: uipath-ubuntu-latest
    if: always() && needs.test.result != 'failure'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        continue-on-error: true
        with:
          name: coverage-xml-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703  # v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
